name: CI

on:
  push:
    branches: [ main, dev ]
    paths-ignore:
      - 'tools/**'
      - '.github/workflows/tools-*.yml'
  pull_request:
    paths-ignore:
      - 'tools/**'
      - '.github/workflows/tools-*.yml'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install Linux Deps
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update

      - name: Run tests
        run: bash scripts/runtests.sh